version: '3.8'

services:
  # Load Balancer (nginx)
  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - nexusdocs-network

  # Application Server Instance 1
  app1:
    build: .
    environment:
      - INSTANCE_ID=1
    networks:
      - nexusdocs-network

  # Application Server Instance 2
  app2:
    build: .
    environment:
      - INSTANCE_ID=2
    networks:
      - nexusdocs-network

  # Application Server Instance 3
  app3:
    build: .
    environment:
      - INSTANCE_ID=3
    networks:
      - nexusdocs-network

networks:
  nexusdocs-network:
    driver: bridge

